### PR TITLE
My story

### PR DESCRIPTION
**Pull request by michael5608**
hi

### CODE REVIEW

**Comment by jim-parry** [comment]
1) you are working in develop, not a feature branch
2) you just pasted the example text from my writeup
3) "update" is not a helpful branch name

**Comment by michael5608** [comment]
My story

**Comment by jim-parry** [comment]
you replaced one segment half with your segment pair?

**Comment by michael5608** [comment]
Hi! I am not sure what replace one segment half with segment pair mean. I did add some details and changed the title

**Comment by jim-parry** [comment]
you have a merge conflict to fix!

**Comment by jim-parry** [comment]
you have a merge conflict to fix!

**Comment by jim-parry** [comment]
oh no - you deleted the first "fortunately"!

**Pull request merged**
