### PR TITLE
Kabilan

### PR DESCRIPTION
**Pull request by Kabug**
Added an unfortunately

### CODE REVIEW

**Comment by jim-parry** [comment]
You need a pair, good & bad, to get injected into the current story.
Better branch name would be tatooine/round1

**Comment by Kabug** [comment]
Added a Fortunately

**Comment by jim-parry** [comment]
Edit the profanity. Replace f**k with smurf, for instance.

**Comment by Kabug** [comment]
Edited Profanity

**Comment by Kabug** [comment]
http://i.imgur.com/04nobDb.png

**Comment by jim-parry** [comment]
better, though still on the offensive side!

**Pull request merged**
